### ISSUE TITLE
List of sound ID's

### ISSUE THREAD

**Issue by leadanymind** [Box-Of-Hats/runelite-plugin-visual-sounds#1]
Hi,

Trying to look into this plugin for some deaf friends of mine. Where can I obtain a list of sound IDs, namely for something like inferno or gauntlet minion attack styles etc.

**Comment by Box-Of-Hats** [comment]
Hi, I was hoping to get a list of those too.
It would be great to show some proper sound names instead of the numbers.

I've manually had to go to places to see playing sound IDs and highlight for certain attacks etc which isn't ideal

**Comment by Box-Of-Hats** [comment]
I've managed to find some incomplete sound lists online. There's potential that these ones could be added with names and then we could start to manually add some others that were useful such as attacks for the nightmare, gauntlet and Jad etc..

**Comment by Box-Of-Hats** [comment]
@leadanymind The plugin now shows sound names as well as IDs. I this helps :)
