### ISSUE TITLE
Add a global block list and include Leviathan specific sounds

### ISSUE THREAD

**Issue by gord5500** [Box-Of-Hats/runelite-plugin-visual-sounds#10]
This is getting abused by players to help them with knowing what prayer to use on the awakened boss 

https://clips.twitch.tv/FlirtyBadSnoodCharlietheUnicorn-_FJfrxyvjM-FMS3h

The sound ids are `7040, 7041, 7030`. 

Happy to make the code changes

**Comment by Box-Of-Hats** [comment]
Hi @gord5500,
I've only just caught up on the news that visual-sounds got taken down. Apologies, I wasn't notified at all about the plugin takedown so I didn't realise this issue was such a high priority.

Reopening this now until the issue is resolved

**Comment by iProdigy** [comment]
Done in https://github.com/runelite/plugin-hub/pull/4755
