### ISSUE TITLE
No Sound IDs in Tzhaar Ket Rak Challenge

### ISSUE THREAD

**Issue by MyNewbAccount** [Box-Of-Hats/runelite-plugin-visual-sounds#16]
While on leagues server, no sound ids populate while within the Tzhaar Ket Rak Challenge. Sound IDs populate while outside, and it does not matter which challenge you enter .

**Comment by Box-Of-Hats** [comment]
Apologies but this is intentional behaviour. The plugin is disabled in a few regions in order to comply with Jagex's plugin guidelines. This includes areas such as the Jad challenges and the inferno
