### ISSUE TITLE
No Sounds shown in Box

### ISSUE THREAD

**Issue by JetFlightGit** [Box-Of-Hats/runelite-plugin-visual-sounds#17]
I installed a few days ago the plugin. It did work for a few minutes, i was messing around settings then and installing some other plugins and then all of the sudden there were no sound ids shown anymore. I tried deinstalling all the other plugins i installed that day, tried reinstalling but nothing reverted the changes and i could not see any sounds anymore

**Comment by Osamu01** [comment]
Seems the plugin is still broken.

**Comment by Box-Of-Hats** [comment]
Hi, can you double check you have game sounds enabled in your client?
