### ISSUE TITLE
Memory leak & crash

### ISSUE THREAD

**Issue by abextm** [Box-Of-Hats/runelite-plugin-visual-sounds#4]
https://github.com/Box-Of-Hats/runelite-plugin-visual-sounds/blob/75299015bcbeb899d032464297347a5dd9e5ead4/src/main/java/com/visualsounds/GameSoundList.java#L16

This leaks memory since `subList` keeps a reference to the parent list so it is never able to free older entries in the list, even though you cannot get to them. This also triggers [JDK-8079136](https://bugs.openjdk.org/browse/JDK-8079136?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel) on older launchers.

You can either just copy the list `new ArrayList(list.subList(...))`, or better use an `ArrayDeque` and pop stuff off the front if its too big.

**Comment by Box-Of-Hats** [comment]
Fixed in #7
