### ISSUE TITLE
Let the colored overwrite blocked IDs

### ISSUE THREAD

**Issue by JetFlightGit** [Box-Of-Hats/runelite-plugin-visual-sounds#5]
Would like to mute everything? Is there an option aswell to mute everything except for a certain selection? Would love if the color also overwrites the blocked list.

**Comment by Mdthompson900** [comment]
I could not agree more on this.

**Comment by Box-Of-Hats** [comment]
I'm not quite sure I understand. Are you saying you'd like an option to mute every sound apart from those on a given list?

**Comment by Mdthompson900** [comment]
> I'm not quite sure I understand. Are you saying you'd like an option to mute every sound apart from those on a given list?

Yes definitely 100%. I'd like the option to be able to list/show only sounds that are listed in tagged sounds. And the original requester would also like to have functionality of tagged sounds still displaying if they're in the muted list as well.

**Comment by JetFlightGit** [comment]
Also when bossing, and some people hear sounds to make it a bit easier. I would like to mute all sounds except for only these few sounds that make it easier.

**Comment by Mdthompson900** [comment]
Yeah ideally I'd like to do something along the lines of zamorak GWD that shows range or mage first so I can prayer flick. Being colour blind and just dumb sometimes it's hard for me to figure out which one is attacking first. For now I have to mute every single sound where it would be much more intuitive to just tag the sounds I want displayed.

**Comment by cmsu224** [comment]
I would also like this, being able to have an option to not display any sounds except for the ones on the list would be a nice QoL.
